### ISSUE TITLE
'TensorSharedVariable' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by engahmed1190** [jayanthkoushik/neural-style#1]
I have an error return back when I am using the fast neural style 

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "fast_neural_style.py", line 56, in <module>
    transformer_net = get_transformer_net(X, weights)
  File "/home/deeplearning/Desktop/CoreMl/neural-style/neural_style/fast_neural_style/transformer_net.py", line 79, in get_transformer_net
    input_ = Input(tensor=X, shape=(3, 256, 256))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1414, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1293, in __init__
    batch_input_shape = K.int_shape(input_tensor)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 451, in int_shape
    shape = x.get_shape()
AttributeError: 'TensorSharedVariable' object has no attribute 'get_shape'
```

The part of the code that present error
```
def get_transformer_net(X, weights=None):
    input_ = Input(tensor=X, shape=(3, 256, 256))
    y = conv_layer(input_, 32, 9)
    y = conv_layer(y, 64, 3, subsample=2)
    y = conv_layer(y, 128, 3, subsample=2)
    y = residual_block(y)
    y = residual_block(y)
    y = residual_block(y)
    y = residual_block(y)
    y = residual_block(y)
    y = conv_layer(y, 64, 3, upsample=2)
```

the command  used

> python fast_neural_style.py eval --content-image chicago.jpg --output-image /home/Desktop/fast-neural-style-keras/images/generated --model stained_glass.h5

**Comment by jayanthkoushik** [comment]
You have to use the Theano backend.

**Comment by engahmed1190** [comment]
Thanks, I appreciate your help
